include: package:flutter_lints/flutter.yaml

analyzer:
  exclude: [build/**]
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

rules:
 avoid_print: false
 prefer_single_quotes: true