// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDM5RznUIrPDiRaizPj6dH_hGWne9EuZB0',
    appId: '1:117540174395:web:1fdd56974efc5131377a1e',
    messagingSenderId: '117540174395',
    projectId: 'learningmanagerflutter',
    authDomain: 'learningmanagerflutter.firebaseapp.com',
    storageBucket: 'learningmanagerflutter.appspot.com',
    measurementId: 'G-B565W698E9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAiQu3NeEtenNGs-g9OciOce1cr8Iu5aU',
    appId: '1:117540174395:android:31253af338692ff7377a1e',
    messagingSenderId: '117540174395',
    projectId: 'learningmanagerflutter',
    storageBucket: 'learningmanagerflutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAx_prLdbyly62qk0Wb8Wmi1JU7v7uyvUA',
    appId: '1:117540174395:ios:875fb7be15650ced377a1e',
    messagingSenderId: '117540174395',
    projectId: 'learningmanagerflutter',
    storageBucket: 'learningmanagerflutter.appspot.com',
    androidClientId: '117540174395-2ao6tfc2j193ap7buk7k3heb1uadjrkh.apps.googleusercontent.com',
    iosClientId: '117540174395-ga7g0tkho9hi1bfm3t2aukivukf5tovj.apps.googleusercontent.com',
    iosBundleId: 'com.app.learningmanagerflutter',
  );
}
